
dofile(core.get_modpath("mylights").."/lightbox.lua")
dofile(core.get_modpath("mylights").."/lightbulbs.lua")
dofile(core.get_modpath("mylights").."/ws.lua")
dofile(core.get_modpath("mylights").."/cubes.lua")
dofile(core.get_modpath("mylights").."/lamppost.lua")
dofile(core.get_modpath("mylights").."/lantern.lua")
dofile(core.get_modpath("mylights").."/sewer_light.lua")
dofile(core.get_modpath("mylights").."/ceilinglights.lua")
dofile(core.get_modpath("mylights").."/machine_bulbs.lua")
dofile(core.get_modpath("mylights").."/machine_cubes.lua")
dofile(core.get_modpath("mylights").."/aliases.lua")
